### ISSUE TITLE
Ladeassistent: UI-justeringer forecast og spotpris

### ISSUE THREAD

**Issue by marikvistad** [VolueSpark/ladeassistent.no#41]
Samleoppgave, kan dele opp ved behov:

1. NO = smartlading. Heading skal være H1
2. Oversettingen her er ikke helt bra. «Oversikt over når det er best å lade elbilen din» f.eks.?
3. Må være på norsk
4. Endre tittel: F.eks. «Syvdagers estimat» (her bør det også stå «spotpriser» i dropdown)
5. Dropdown bør være mindre. Må finne en annen designløsning hvis det ikke er mulig/blir bra
6. Mindre spacing mellom enden på tekst og ikon (16px)
7. Kan fjerne divider
8. Ikon på linje med tekst (første linje). Omformuler tekst til f.eks. «Prisene er gjennomsnitt i øre/kWh innenfor de gitte tidsintervallene. Estimatene er basert på analyser, og oppdateres hver time.» Tilleggsspørsmål: Burde vi fremheve at det er gjennomsnittspriser?
9. Område under diagram: Utvikle som ihht. skissert løsning hvis det er mulig?
10. Reduser whitespace mellom innhold og footer
11. Endre oppløsning på graf når det er små beløp, så slipper man knøttsmå barer
12. Oversettes ikke til engelsk
13. Oversettes ikke til engelsk
14. Infotekst spotpriser har en t for mye: Spotprisene oppdateres _hvert_ dag og reflekterer de reelle prisene for øyeblikket.

![Image](https://user-images.githubusercontent.com/111277983/258805476-e2617c55-fdf5-4f99-b326-e6eed40ae50f.png)
![Image](https://user-images.githubusercontent.com/111277983/258805475-aa3bc4a6-1932-4aff-9a62-fcd8183a7be2.png)

**Comment by trulshj** [comment]
Også på **11.** så kan vi vurdere å vise negative priser, men det er sikkert mer styr enn det er verdt.

**Comment by marikvistad** [comment]
Moved to Volue board
